# This is a basic workflow to help you get started with Actions

name: Build and deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [feature/*]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: install yarn, resolve dependencies and build
        run: |
          npm install -g yarn
          yarn
          yarn build

      - name: upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name stagingmezackedev -d '$web' -s ./build

      - name: purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name bulk-up-zacke-dev --name stagingmezackedev --resource-group zacke.dev

      - name: logout
        run: |
          az logout
